AWSTemplateFormatVersion: "2010-09-09"
Description: "Bucket S3 for web content"

Parameters:
  webBucketName:
    Type: "String"
    AllowedPattern: "^[a-zA-Z0-9]+[a-zA-Z0-9-]+[a-zA-Z0-9]+$"
    Default: "magic-ball-web-bucket"

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: !Ref "webBucketName"
      WebsiteConfiguration:
        IndexDocument: "index.html"
        ErrorDocument: "error.html"
  webBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      PolicyDocument:
        Id: magic-ball-WebBucketPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join 
              - ''
              - - 'arn:aws:s3:::'
                - !Ref s3Bucket
                - /*
      Bucket: !Ref s3Bucket


Outputs:
  WebsiteURL:
    Value: !GetAtt [s3Bucket, WebsiteURL]
    Description: URL for website hosted on S3